# Configuration of the working directories
# If you a relative path, note that the reference is the location of "zenodup.py" script.  

# Please see README.md for more detailed documentation

# input/output directories for conference data
input_base: "INPUT"
output_base: "OUTPUT"

# support directories
depositions_dir : "support/depositions/"
logging_dir : "support/logging/"
assignments_dir : "support/assignments/"
packages_dir : "support/package/"

# directoy for updated metadata files (not part of regular workflow)
update_dir : "support/updated_metadata/"